from app.db.supabase import supabase


class DiagnosticRepository:

    @staticmethod
    def get_findings(investigation_id: str):
        # First get the agent runs belonging to this investigation
        runs_response = (
            supabase
            .table("agent_runs")
            .select("id")
            .eq("investigation_id", investigation_id)
            .execute()
        )

        run_ids = [run["id"] for run in runs_response.data]

        if not run_ids:
            return []

        # Get findings generated by those runs
        response = (
            supabase
            .table("agent_findings")
            .select("*")
            .in_("agent_run_id", run_ids)
            .order("created_at", desc=True)
            .execute()
        )

        return response.data

    @staticmethod
    def get_evidence(investigation_id: str):
        findings = DiagnosticRepository.get_findings(investigation_id)

        finding_ids = [finding["id"] for finding in findings]

        if not finding_ids:
            return []

        response = (
            supabase
            .table("finding_evidence")
            .select("*")
            .in_("finding_id", finding_ids)
            .order("evidence_timestamp", desc=True)
            .execute()
        )

        return response.data

    @staticmethod
    def get_driver_candidates(investigation_id: str):
        response = (
            supabase
            .table("driver_candidates")
            .select("*")
            .eq("investigation_id", investigation_id)
            .order("rank")
            .execute()
        )

        return response.data

    @staticmethod
    def get_entity_logs(entity_type: str, entity_id: str):

        response = (
            supabase
            .table("audit_logs")
            .select("*")
            .eq("entity_type", entity_type)
            .eq("entity_id", entity_id)
            .order("created_at", desc=True)
            .execute()
        )

        return response.data